---
templateDir: .openapi-generator/templates
additionalProperties:
  packageName: Raiffeisenbank Premium API client library
  apiPackage: PremiumAPI
  UserId: VitexSoftware
  RepoId: php-vitexsoftware-rbczpremiumapi
  infoEmail: info@vitexsoftware.cz
  allowUnicodeIdentifiers: true
  artifactVersion: 1.3.1
  invokerPackage: VitexSoftware\Raiffeisenbank
  modelPackage: Model
  variableNamingConvention: camelCase
  composerPackageName: vitexsoftware/rbczpremiumapi
files:
  AUTHORS.md: {}
  composer.json: {}
  ApiClient.mustache:
      folder: lib
      destinationFilename: ApiClient.php
  Statementor.mustache:
      folder: lib
      destinationFilename: Statementor.php
  Transactor.mustache:
      folder: lib
      destinationFilename: Transactor.php
  bootstrap.php:
      folder: test
  RateLimiter.mustache:
    folder: lib/RateLimit
    destinationFilename: RateLimiter.php
  RateLimitStoreInterface.mustache:
    folder: lib/RateLimit
    destinationFilename: RateLimitStoreInterface.php
  SqlDialect.mustache:
    folder: lib/RateLimit
    destinationFilename: SqlDialect.php
  RateLimitMode.mustache:
    folder: lib/RateLimit
    destinationFilename: RateLimitMode.php
  RateLimitExceededException.mustache:
    folder: lib/RateLimit
    destinationFilename: RateLimitExceededException.php
  PdoRateLimitStore.mustache:
    folder: lib/RateLimit
    destinationFilename: PdoRateLimitStore.php
  JsonRateLimitStore.mustache:
    folder: lib/RateLimit
    destinationFilename: JsonRateLimitStore.php
  RateLimiterTest.mustache:
    folder: test/RateLimit
    destinationFilename: RateLimiterTest.php
  RateLimitStoreInterfaceTest.mustache:
    folder: test/RateLimit
    destinationFilename: RateLimitStoreInterfaceTest.php
  SqlDialectTest.mustache:
    folder: test/RateLimit
    destinationFilename: SqlDialectTest.php
